
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chetx
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        Color c = new Color(240, 230, 140);
        this.getContentPane().setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrar_Usuario = new javax.swing.JButton();
        mostrar_Entradas_Usuarios = new javax.swing.JButton();
        controlar_Entradas = new javax.swing.JButton();
        consultar_Usuarios = new javax.swing.JButton();
        modificar_Usuarios = new javax.swing.JButton();
        cerrar_sesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        registrar_Usuario.setBackground(new java.awt.Color(240, 248, 255));
        registrar_Usuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        registrar_Usuario.setText("Registrar Usuario");
        registrar_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_UsuarioActionPerformed(evt);
            }
        });

        mostrar_Entradas_Usuarios.setBackground(new java.awt.Color(240, 248, 255));
        mostrar_Entradas_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        mostrar_Entradas_Usuarios.setText("Mostrar entradas \nde usuarios");
        mostrar_Entradas_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrar_Entradas_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_Entradas_UsuariosActionPerformed(evt);
            }
        });

        controlar_Entradas.setBackground(new java.awt.Color(240, 248, 255));
        controlar_Entradas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        controlar_Entradas.setText("Controlar Entradas");
        controlar_Entradas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        controlar_Entradas.setDefaultCapable(false);
        controlar_Entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlar_EntradasActionPerformed(evt);
            }
        });

        consultar_Usuarios.setBackground(new java.awt.Color(240, 248, 255));
        consultar_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        consultar_Usuarios.setText("Consultar Usuarios");
        consultar_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultar_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_UsuariosActionPerformed(evt);
            }
        });

        modificar_Usuarios.setBackground(new java.awt.Color(240, 248, 255));
        modificar_Usuarios.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        modificar_Usuarios.setText("Modificar Usuarios");
        modificar_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_UsuariosActionPerformed(evt);
            }
        });

        cerrar_sesion.setBackground(new java.awt.Color(240, 248, 255));
        cerrar_sesion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cerrar_sesion.setText("Cerrar Sesión");
        cerrar_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar_sesionActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPinoSF.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 56)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(207, 167, 16));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrar_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrar_Entradas_Usuarios))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(controlar_Entradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultar_Usuarios))
                    .addComponent(modificar_Usuarios))
                .addGap(191, 191, 191))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cerrar_sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jLabel3)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cerrar_sesion)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(registrar_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(mostrar_Entradas_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(controlar_Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(consultar_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(modificar_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar_sesionActionPerformed
        this.setVisible(false);
        new login().setVisible(true);
        
    }//GEN-LAST:event_cerrar_sesionActionPerformed

    private void controlar_EntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlar_EntradasActionPerformed
        this.setVisible(false);
        new controlar_Acceso().setVisible(true);
    }//GEN-LAST:event_controlar_EntradasActionPerformed

    private void registrar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_UsuarioActionPerformed
        try{
            String [] opc = {"Administrador", "Inquilino"};
            String resp = (String)JOptionPane.showInputDialog(null, "Tipo de usuario a registrar",null, JOptionPane.DEFAULT_OPTION, null, opc, opc[0]);
            if(resp.equals(opc[0])){
                this.setVisible(false);
                new Registrar_admin().setVisible(true);
            }else{
                this.setVisible(false);
                new Registrar_inquilino().setVisible(true);
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_registrar_UsuarioActionPerformed

    private void mostrar_Entradas_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_Entradas_UsuariosActionPerformed
        try{
            String [] opc = {"Inquilinos", "Visitantes"};
            String resp = (String)JOptionPane.showInputDialog(null, "¿De que usuarios quieres mostrar sus entradas?",null, JOptionPane.DEFAULT_OPTION, null, opc, opc[0]);
            if(resp.equals(opc[0])){
                this.setVisible(false);
                new mostrar_Registros_Inquilinos().setVisible(true);
            }else{
                this.setVisible(false);
                new mostrar_Registros_Visitas().setVisible(true);
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_mostrar_Entradas_UsuariosActionPerformed

    private void consultar_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_UsuariosActionPerformed
        this.setVisible(false);
        new consultar_Usuarios().setVisible(true);
    }//GEN-LAST:event_consultar_UsuariosActionPerformed

    private void modificar_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_UsuariosActionPerformed
        this.setVisible(false);
        new modificar_Usuarios().setVisible(true);
    }//GEN-LAST:event_modificar_UsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar_sesion;
    private javax.swing.JButton consultar_Usuarios;
    private javax.swing.JButton controlar_Entradas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton modificar_Usuarios;
    private javax.swing.JButton mostrar_Entradas_Usuarios;
    private javax.swing.JButton registrar_Usuario;
    // End of variables declaration//GEN-END:variables
}
