

import com.itextpdf.kernel.pdf.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.Document;
import sun.swing.SwingUtilities2.Section;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chetx
 */
public class mostrar_Registros_Inquilinos extends javax.swing.JFrame {

    static Connection cn;
    static Statement s;
    static ResultSet rs;
    static String id, nombre, apellidoP, fecha, hora, user;
    static TableRowSorter filtro;
    static DefaultTableModel tabla;
    static File archivoSalida;
    static FileOutputStream flujoSalida;
    static PrintWriter archivoTxt;
    /**
     * Creates new form mostrar_Registros_Inquilinos
     */
    public mostrar_Registros_Inquilinos() {
        initComponents();
        Color c = new Color(240, 230, 140);
        this.getContentPane().setBackground(c);
        listar();
    }

    public int buscar_user(){
        int r = 0;
        try{
            Connection conect = null;
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            String sql="SELECT ID FROM INQUILINOS_ENTRADAS WHERE ID ="+n_buscar.getText();
            rs = st.executeQuery(sql);
            if(rs.next()){
                r = 1;
            }
            rs.close();
        }catch(Exception e){
            
        }
        return r;
    }
    
    public int buscar_nombre(){
        int r = 0;
        try{
            Connection conect = null;
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            String sql="SELECT NOMBRE FROM INQUILINOS_ENTRADAS WHERE NOMBRE ='"+n_buscar.getText()+"'";
            rs = st.executeQuery(sql);
            if(rs.next()){
                r = 1;
            }
            rs.close();
        }catch(Exception e){
            
        }
        return r;
    }
    
    
    public void listar() {

       Object [] alNivel2;
       String [] titulo = {"Id", "Nombre", "Apellido Paterno", "Fecha", "Hora"};
            tabla = new DefaultTableModel(null, titulo);
        try {
            
            Connection conect = null;
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            String sql="SELECT ID, NOMBRE, APELLIDOP, FECHA, HORA FROM INQUILINOS_ENTRADAS WHERE FECHA = TO_CHAR(FECHA, 'DD/MM/YYYY') ORDER BY FECHA DESC";
            rs = st.executeQuery(sql); 
            
            while (rs.next()) {
                id = rs.getString("ID");
                nombre = rs.getString("NOMBRE");
                apellidoP = rs.getString("APELLIDOP");
                fecha = rs.getString("FECHA");
                hora = rs.getString("HORA");
                Object [] row ={id,nombre,apellidoP,fecha.substring(0, 10), hora};
                tabla.addRow(row);
                
            }
            rs.close();
           
        } catch (SQLException sqle) {
            System.out.println("Error SQL....." + sqle);
        }
        datosInquilinos.setModel(tabla);
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosInquilinos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        n_buscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        restablecer = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(207, 167, 16));
        jLabel1.setText("Entradas de Inquilinos");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 83, 15), 3));

        regresar.setBackground(new java.awt.Color(240, 248, 255));
        regresar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        datosInquilinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Fecha", "Hora"
            }
        ));
        jScrollPane1.setViewportView(datosInquilinos);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logitoV3.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("ID de Usuario/Nombre:");
        jLabel3.setToolTipText("");

        n_buscar.setToolTipText("La fecha debe ser en formato dd/mm/yy  o en formato dd/mm/yyyy ");
        n_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n_buscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                n_buscarKeyTyped(evt);
            }
        });

        buscar.setBackground(new java.awt.Color(240, 248, 255));
        buscar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        restablecer.setBackground(new java.awt.Color(240, 248, 255));
        restablecer.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        restablecer.setText("Restablecer");
        restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restablecerActionPerformed(evt);
            }
        });

        imprimir.setBackground(new java.awt.Color(240, 248, 255));
        imprimir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        imprimir.setText("Guardar");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imprimir)
                        .addGap(36, 36, 36)
                        .addComponent(restablecer)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regresar)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(n_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(restablecer)
                    .addComponent(imprimir))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.setVisible(false);
        if(new login().getTipo() == 1){
            new menu().setVisible(true);
        }else{
            new menu_inquilino().setVisible(true);
        }
    }//GEN-LAST:event_regresarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try{
            if(n_buscar.getText().matches("^[0-9]*$")){
                if(n_buscar.getText().equals("")){
                    filtro = new TableRowSorter(datosInquilinos.getModel());
                    datosInquilinos.setRowSorter(filtro);
                    filtro.setRowFilter(RowFilter.regexFilter(n_buscar.getText(), 0));
                }
                else if(buscar_user() == 1){
                    filtro = new TableRowSorter(datosInquilinos.getModel());
                    datosInquilinos.setRowSorter(filtro);
                    filtro.setRowFilter(RowFilter.regexFilter(n_buscar.getText(), 0));
                }else{
                    JOptionPane.showMessageDialog(null, "No existe el usuario", null, JOptionPane.ERROR_MESSAGE);
                    n_buscar.setText("");
                    n_buscar.requestFocus();
                }
            }else if(n_buscar.getText().matches("^[a-zA-Z]*$")){
                if(n_buscar.getText().equals("")){
                    filtro = new TableRowSorter(datosInquilinos.getModel());
                    datosInquilinos.setRowSorter(filtro);
                    filtro.setRowFilter(RowFilter.regexFilter(n_buscar.getText(), 0));
                }
                else if(buscar_nombre() == 1){
                    filtro = new TableRowSorter(datosInquilinos.getModel());
                    datosInquilinos.setRowSorter(filtro);
                    filtro.setRowFilter(RowFilter.regexFilter(n_buscar.getText(), 1));
                }else{
                    JOptionPane.showMessageDialog(null, "No existe el usuario o esta mal escrito", null, JOptionPane.ERROR_MESSAGE);
                    n_buscar.setText("");
                    n_buscar.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Solo se aceptan números o letras", null, JOptionPane.WARNING_MESSAGE);
                n_buscar.setText("");
                n_buscar.requestFocus();
            }
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void n_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n_buscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscar.doClick();
        }
    }//GEN-LAST:event_n_buscarKeyPressed

    private void restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restablecerActionPerformed
        n_buscar.setText("");
       if(n_buscar.getText().equals("")){
          filtro = new TableRowSorter(datosInquilinos.getModel());
          datosInquilinos.setRowSorter(filtro);
          filtro.setRowFilter(RowFilter.regexFilter(n_buscar.getText(), 0));
       }
       n_buscar.requestFocus();
    }//GEN-LAST:event_restablecerActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        
        try{
            archivoSalida  = new File("C:\\Users\\js98v\\Desktop\\pdfs\\Registros_Entradas_Inquilinos.txt");
            flujoSalida  = new FileOutputStream(archivoSalida);
            archivoTxt = new PrintWriter(flujoSalida);
            archivoTxt.println("Fecha     | Hora  | Id   | Nombre | Apellido Paterno ");
            Connection conect = null;
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            String sql="SELECT ID, NOMBRE, APELLIDOP, FECHA, HORA FROM INQUILINOS_ENTRADAS WHERE FECHA = TO_CHAR(FECHA, 'DD/MM/YYYY') ORDER BY FECHA DESC";
            rs = st.executeQuery(sql); // ejecuta la query
            
            while (rs.next()) {
                id = rs.getString("ID");
                nombre = rs.getString("NOMBRE");
                apellidoP = rs.getString("APELLIDOP");
                fecha = rs.getString("FECHA");
                hora = rs.getString("HORA");
                archivoTxt.println(fecha.substring(0, 10)+"  "+hora+"  "+id+"  "+nombre+"   "+apellidoP);
                
            }
            archivoTxt.close();
            rs.close();
            JOptionPane.showMessageDialog(null, "Guardado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo guardar", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_imprimirActionPerformed

    private void n_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n_buscarKeyTyped
        if(n_buscar.getText().length()>9){
            evt.consume();
        }
    }//GEN-LAST:event_n_buscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mostrar_Registros_Inquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mostrar_Registros_Inquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mostrar_Registros_Inquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mostrar_Registros_Inquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mostrar_Registros_Inquilinos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTable datosInquilinos;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n_buscar;
    private javax.swing.JButton regresar;
    private javax.swing.JButton restablecer;
    // End of variables declaration//GEN-END:variables
}
