/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Chetx
 */
public class Registrar_admin extends javax.swing.JFrame {
    static Connection cn;
    static Statement s;
    static ResultSet rs;
    static ResultSetMetaData rsmd;
    static String nombre, telefono, apellidoP, apellidoM, genero, calle, contraseña;
    static int id, edad, ocupantes, vehiculos, vivienda, tipo;
    /**
     * Creates new form Registrar_admin
     */
    public Registrar_admin() {
        initComponents();
        Color c = new Color(240, 230, 140);
        this.getContentPane().setBackground(c);
        id_nuevo();
        //id_admin.setText(id);
    }
    
    public void id_nuevo(){
        String sql ="SELECT MAX(ID) FROM USUARIOS WHERE ID LIKE '2201%'";
        Connection conect = null;
        try {
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            ResultSetMetaData rsmd = rs.getMetaData();
            if(rs.next()){
               id = rs.getInt("MAX(ID)") + 1;
               id_admin.setText(String.valueOf(id));
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }finally{
            try {
                conect.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Error de desconexión", JOptionPane.ERROR_MESSAGE);
            }
        }

    }
    
    public int registrar(){
        int resultado = 0;
        nombre = nombre_admin.getText();
        apellidoP = apellidoP_admin.getText();
        apellidoM = apellidoM_admin.getText();
        calle = calle_admin.getText();
        contraseña = pass_admin.getText();
        edad = Integer.parseInt(edad_admin.getText());
        telefono = telefono_admin.getText();
        ocupantes = Integer.parseInt(ocup_admin.getText());
        vehiculos = Integer.parseInt(veh_admin.getText());
        vivienda = Integer.parseInt(casaNo_admin.getText());
        
        String sql="INSERT INTO USUARIOS VALUES("+id_admin.getText()+",'"+nombre+"', '"+apellidoP+"', '"+ apellidoM+"', "+edad+", '"+genero+"','"
                                                 +telefono+"',"+ocupantes+", "+vehiculos+" , '"+calle+"' , "+vivienda+", '"+contraseña+"', 1)";
        
        Connection conect = null;
        try {
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                resultado=1;
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }finally{
            try {
                conect.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Error de desconexión", JOptionPane.ERROR_MESSAGE);
            }
        }

        return resultado;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id_admin = new javax.swing.JLabel();
        nombre_admin = new javax.swing.JTextField();
        apellidoP_admin = new javax.swing.JTextField();
        apellidoM_admin = new javax.swing.JTextField();
        edad_admin = new javax.swing.JTextField();
        telefono_admin = new javax.swing.JTextField();
        opc_hombre = new javax.swing.JCheckBox();
        opc_mujer = new javax.swing.JCheckBox();
        ocup_admin = new javax.swing.JTextField();
        veh_admin = new javax.swing.JTextField();
        calle_admin = new javax.swing.JTextField();
        casaNo_admin = new javax.swing.JTextField();
        pass_admin = new javax.swing.JTextField();
        registrar_administrador = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(920, 720));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("ID Administrador");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Nombre(s)");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("Apellido Paterno");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("Apellido Materno");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setText("Edad");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Telefono");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("Genero");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setText("No. de Ocupantes");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setText("No. de Vehiculos");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setText("Calle");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setText("Número de Casa");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel12.setText("Contraseña");

        id_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        id_admin.setText("-----");

        nombre_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombre_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombre_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_adminKeyTyped(evt);
            }
        });

        apellidoP_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        apellidoP_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apellidoP_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoP_adminKeyTyped(evt);
            }
        });

        apellidoM_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        apellidoM_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apellidoM_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoM_adminKeyTyped(evt);
            }
        });

        edad_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edad_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edad_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edad_adminKeyTyped(evt);
            }
        });

        telefono_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefono_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefono_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono_adminKeyTyped(evt);
            }
        });

        opc_hombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        opc_hombre.setText("Hombre");
        opc_hombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opc_hombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opc_hombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                opc_hombreKeyReleased(evt);
            }
        });

        opc_mujer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        opc_mujer.setText("Mujer");
        opc_mujer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opc_mujer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opc_mujerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                opc_mujerKeyReleased(evt);
            }
        });

        ocup_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ocup_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ocup_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ocup_adminKeyTyped(evt);
            }
        });

        veh_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        veh_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                veh_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                veh_adminKeyTyped(evt);
            }
        });

        calle_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        calle_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calle_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                calle_adminKeyTyped(evt);
            }
        });

        casaNo_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        casaNo_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                casaNo_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                casaNo_adminKeyTyped(evt);
            }
        });

        pass_admin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pass_admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_adminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_adminKeyTyped(evt);
            }
        });

        registrar_administrador.setBackground(new java.awt.Color(240, 248, 255));
        registrar_administrador.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        registrar_administrador.setText("Registrar");
        registrar_administrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar_administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_administradorActionPerformed(evt);
            }
        });
        registrar_administrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registrar_administradorKeyPressed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(240, 248, 255));
        cancelar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(240, 248, 255));
        regresar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        regresar.setText("Regresar");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPinoSF.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(207, 167, 16));
        jLabel15.setText("Registrar Administrador");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 83, 15), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(regresar)
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opc_hombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(opc_mujer))
                                    .addComponent(nombre_admin)
                                    .addComponent(apellidoP_admin)
                                    .addComponent(apellidoM_admin)
                                    .addComponent(edad_admin)
                                    .addComponent(telefono_admin)
                                    .addComponent(ocup_admin)
                                    .addComponent(veh_admin)
                                    .addComponent(calle_admin)
                                    .addComponent(casaNo_admin)
                                    .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65)
                                .addComponent(id_admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(registrar_administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrar_administrador)
                        .addGap(77, 77, 77)
                        .addComponent(cancelar)
                        .addGap(271, 271, 271))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(regresar))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id_admin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellidoP_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apellidoM_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edad_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(telefono_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(opc_hombre)
                            .addComponent(opc_mujer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ocup_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(veh_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(calle_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(casaNo_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(60, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_administradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_administradorActionPerformed
        try{
            boolean validacion = false, val_p= false, val_m = false, val_c = false, valS = false;
           char [] s ={'@','!','"','#','$','%','&','/','(',')','=','?','¿','¡','-',':',';','|','°','¬','*','+','.',',','_','<','>','[',']','{','}','´','¨','^','`',
                        '1','2','3','4','5','6','7','8','9','0'};
           char [] c ={'@','!','"','#','$','%','&','/','(',')','=','?','¿','¡','-',':',';','|','°','¬','*','+','.',',','_','<','>','[',']','{','}','´','¨','^','`'};
               for(int i = 0; i<nombre_admin.getText().length();i++){
                   for(int j = 0;j<45; j++){
                       if(nombre_admin.getText().charAt(i) == s[j]){
                           valS = true;
                       }
                   }
                   if(!valS){
                    if(nombre_admin.getText().charAt(i) == ' ' && nombre_admin.getText().charAt(0) != ' '){
                        validacion = true;
                    }   
                   }
               }
               validacion = false;
               for(int i = 0; i<apellidoP_admin.getText().length();i++){
                   for(int j = 0;j<45; j++){
                       if(apellidoP_admin.getText().charAt(i) == s[j]){
                           val_p= true;
                       }
                   }
                   if(!val_p){
                    if(apellidoP_admin.getText().charAt(0) != ' ' && apellidoP_admin.getText().charAt(i) == ' '){
                        validacion = true;
                    }   
                   }
               }
               validacion = false;
               for(int i = 0; i<apellidoM_admin.getText().length();i++){
                   for(int j = 0;j<45; j++){
                       if(apellidoM_admin.getText().charAt(i) == s[j]){
                           val_m = true;
                       }
                   }
                   if(!val_m){
                    if(apellidoM_admin.getText().charAt(0) != ' ' && apellidoM_admin.getText().charAt(i) == ' '){
                        validacion = true;
                    }   
                   }
               }
               validacion = false;
               for(int i = 0; i<calle_admin.getText().length();i++){
                   for(int j = 0;j<35; j++){
                       if(calle_admin.getText().charAt(i) == c[j]){
                           val_c = true;
                       }
                   }
                   if(!val_c){
                    if(calle_admin.getText().charAt(0) != ' ' && calle_admin.getText().charAt(i) == ' '){
                        validacion = true;
                    }   
                   }
               }
               
            if(!id_admin.getText().isEmpty() && !nombre_admin.getText().isEmpty() && !apellidoP_admin.getText().isEmpty() && !apellidoM_admin.getText().isEmpty() && !edad_admin.getText().isEmpty()
               && !telefono_admin.getText().isEmpty() && !ocup_admin.getText().isEmpty() && !veh_admin.getText().isEmpty() && 
                    !calle_admin.getText().isEmpty() && !casaNo_admin.getText().isEmpty() && !pass_admin.getText().isEmpty()){
                if(!valS && (validacion || nombre_admin.getText().matches("^[a-zA-Z]*$"))){
                    if(!val_p && (validacion || apellidoP_admin.getText().matches("^[a-zA-Z]*$"))){
                        if(apellidoM_admin.getText().matches("^[a-zA-Z]*$")){
                            if(!calle_admin.getText().startsWith(" ")){
                                if(edad_admin.getText().matches("^[0-9]*$")){
                                    if(telefono_admin.getText().matches("^[0-9]*$")){
                                        if(opc_hombre.isSelected() && !opc_mujer.isSelected()){
                                            genero = "H";
                                            if(registrar()==1){
                                                JOptionPane.showMessageDialog(null, "Registrado");
                                                nombre_admin.setText("");
                                                apellidoP_admin.setText("");
                                                apellidoM_admin.setText("");
                                                calle_admin.setText("");
                                                pass_admin.setText("");
                                                edad_admin.setText("");
                                                telefono_admin.setText("");
                                                ocup_admin.setText("");
                                                veh_admin.setText("");
                                                casaNo_admin.setText("");
                                                opc_hombre.setSelected(false);
                                                id_nuevo();
                                            }else{
                                                JOptionPane.showMessageDialog(null, "No Registrado", null, JOptionPane.WARNING_MESSAGE);
                                                nombre_admin.setText("");
                                                apellidoP_admin.setText("");
                                                apellidoM_admin.setText("");
                                                calle_admin.setText("");
                                                pass_admin.setText("");
                                                edad_admin.setText("");
                                                telefono_admin.setText("");
                                                ocup_admin.setText("");
                                                veh_admin.setText("");
                                                casaNo_admin.setText("");
                                                opc_hombre.setSelected(false);
                                            }
                                        }else if(!opc_hombre.isSelected() && opc_mujer.isSelected()){
                                            genero = "M";
                                            if(registrar()==1){
                                                JOptionPane.showMessageDialog(null, "Registrado");
                                                nombre_admin.setText("");
                                                apellidoP_admin.setText("");
                                                apellidoM_admin.setText("");
                                                calle_admin.setText("");
                                                pass_admin.setText("");
                                                edad_admin.setText("");
                                                telefono_admin.setText("");
                                                ocup_admin.setText("");
                                                veh_admin.setText("");
                                                casaNo_admin.setText("");
                                                opc_mujer.setSelected(false);
                                                id_nuevo();
                                            }else{
                                                JOptionPane.showMessageDialog(null, "No Registrado", null, JOptionPane.WARNING_MESSAGE);
                                                nombre_admin.setText("");
                                                apellidoP_admin.setText("");
                                                apellidoM_admin.setText("");
                                                calle_admin.setText("");
                                                pass_admin.setText("");
                                                edad_admin.setText("");
                                                telefono_admin.setText("");
                                                ocup_admin.setText("");
                                                veh_admin.setText("");
                                                casaNo_admin.setText("");
                                                opc_mujer.setSelected(false);
                                            }
                                        }else if(!opc_hombre.isSelected() && !opc_mujer.isSelected()){
                                            JOptionPane.showMessageDialog(null, "No se ha seleccionado genero", null, JOptionPane.WARNING_MESSAGE);
                                        }else{
                                            JOptionPane.showMessageDialog(null, "Selecciona un solo genero", null, JOptionPane.WARNING_MESSAGE);
                                            opc_hombre.setSelected(false);
                                            opc_mujer.setSelected(false);
                                        }
                                }else{
                                    JOptionPane.showMessageDialog(null, "!Caracteres invalidos!.", "Alerta", JOptionPane.ERROR_MESSAGE);
                                    telefono_admin.setText("");
                                    telefono_admin.requestFocus();
                                }
                                }else{
                                    JOptionPane.showMessageDialog(null, "!Caracteres invalidos!.", "Alerta", JOptionPane.ERROR_MESSAGE);
                                    edad_admin.setText("");
                                    edad_admin.requestFocus();
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "El campo de calle no debe empezar con espacio\n"+ "en blanco o estar vacia.", "Alerta", JOptionPane.ERROR_MESSAGE);
                                calle_admin.setText("");
                                calle_admin.requestFocus();
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Solo se permiten letras en el apellido materno\n"+"ni espacios en blanco al principio.", "Alerta", JOptionPane.ERROR_MESSAGE);
                            apellidoM_admin.setText("");
                            apellidoM_admin.requestFocus();
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Solo se permiten letras en el apellido paterno\n"+"ni espacios en blanco al principio.", "Alerta", JOptionPane.ERROR_MESSAGE);
                        apellidoP_admin.setText("");
                        apellidoP_admin.requestFocus();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Solo se permiten letras en el nombre.\n"+ "sin espacios al principio.", "Alerta", JOptionPane.ERROR_MESSAGE);
                    nombre_admin.setText("");
                    nombre_admin.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Alerta!", JOptionPane.WARNING_MESSAGE);
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "¡Caracteres invalidos!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrar_administradorActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        JOptionPane.showMessageDialog(null, "Regresando al menu");
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void nombre_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_adminKeyTyped
        if(nombre_admin.getText().length()>19){
            evt.consume();
        }
    }//GEN-LAST:event_nombre_adminKeyTyped

    private void apellidoP_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoP_adminKeyTyped
        if(apellidoP_admin.getText().length()>19){
            evt.consume();
        }
    }//GEN-LAST:event_apellidoP_adminKeyTyped

    private void apellidoM_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoM_adminKeyTyped
        if(apellidoM_admin.getText().length()>19){
            evt.consume();
        }
    }//GEN-LAST:event_apellidoM_adminKeyTyped

    private void edad_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edad_adminKeyTyped
        if(edad_admin.getText().length()>2){
            evt.consume();
        }
    }//GEN-LAST:event_edad_adminKeyTyped

    private void telefono_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_adminKeyTyped
        if(telefono_admin.getText().length()>9){
            evt.consume();
        }
    }//GEN-LAST:event_telefono_adminKeyTyped

    private void ocup_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ocup_adminKeyTyped
        if(ocup_admin.getText().length()>1){
            evt.consume();
        }
    }//GEN-LAST:event_ocup_adminKeyTyped

    private void veh_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_veh_adminKeyTyped
        if(veh_admin.getText().length()>1){
            evt.consume();
        }
    }//GEN-LAST:event_veh_adminKeyTyped

    private void calle_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calle_adminKeyTyped
        if(calle_admin.getText().length()>49){
            evt.consume();
        }
    }//GEN-LAST:event_calle_adminKeyTyped

    private void casaNo_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_casaNo_adminKeyTyped
        if(casaNo_admin.getText().length()>4){
            evt.consume();
        }
    }//GEN-LAST:event_casaNo_adminKeyTyped

    private void pass_adminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_adminKeyTyped
        if(pass_admin.getText().length()>9){
            evt.consume();
        }
    }//GEN-LAST:event_pass_adminKeyTyped

    private void opc_hombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opc_hombreKeyReleased
        
        
    }//GEN-LAST:event_opc_hombreKeyReleased

    private void opc_mujerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opc_mujerKeyReleased
        
    }//GEN-LAST:event_opc_mujerKeyReleased

    private void nombre_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_adminKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            apellidoP_admin.requestFocus();
        }
    }//GEN-LAST:event_nombre_adminKeyPressed

    private void apellidoP_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoP_adminKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            apellidoM_admin.requestFocus();
        }
    }//GEN-LAST:event_apellidoP_adminKeyPressed

    private void apellidoM_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoM_adminKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edad_admin.requestFocus();
        }
    }//GEN-LAST:event_apellidoM_adminKeyPressed

    private void edad_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edad_adminKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            telefono_admin.requestFocus();
        }
    }//GEN-LAST:event_edad_adminKeyPressed

    private void telefono_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_adminKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            opc_hombre.requestFocus();
        }
    }//GEN-LAST:event_telefono_adminKeyPressed

    private void ocup_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ocup_adminKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            veh_admin.requestFocus();
        }
    }//GEN-LAST:event_ocup_adminKeyPressed

    private void veh_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_veh_adminKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calle_admin.requestFocus();
        }
    }//GEN-LAST:event_veh_adminKeyPressed

    private void calle_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calle_adminKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            casaNo_admin.requestFocus();
        }
    }//GEN-LAST:event_calle_adminKeyPressed

    private void casaNo_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_casaNo_adminKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            pass_admin.requestFocus();
        }
    }//GEN-LAST:event_casaNo_adminKeyPressed

    private void pass_adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_adminKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            registrar_administrador.requestFocus();
        }
    }//GEN-LAST:event_pass_adminKeyPressed

    private void registrar_administradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrar_administradorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          registrar_administrador.doClick();
        }
    }//GEN-LAST:event_registrar_administradorKeyPressed

    private void opc_hombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opc_hombreKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            opc_hombre.setSelected(true);
            ocup_admin.requestFocus();
        }
    }//GEN-LAST:event_opc_hombreKeyPressed

    private void opc_mujerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opc_mujerKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            opc_mujer.setSelected(true);
            ocup_admin.requestFocus();
        }
    }//GEN-LAST:event_opc_mujerKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoM_admin;
    private javax.swing.JTextField apellidoP_admin;
    private javax.swing.JTextField calle_admin;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField casaNo_admin;
    private javax.swing.JTextField edad_admin;
    private javax.swing.JLabel id_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre_admin;
    private javax.swing.JTextField ocup_admin;
    private javax.swing.JCheckBox opc_hombre;
    private javax.swing.JCheckBox opc_mujer;
    private javax.swing.JTextField pass_admin;
    private javax.swing.JButton registrar_administrador;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField telefono_admin;
    private javax.swing.JTextField veh_admin;
    // End of variables declaration//GEN-END:variables
}
