/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Chetx
 */
public class Registrar_inquilino extends javax.swing.JFrame {
    static Connection cn;
    static Statement s;
    static ResultSet rs;
    static ResultSetMetaData rsmd;
    static String nombre, telefono, apellidoP, apellidoM, genero, calle, contraseña;
    static int id, edad, ocupantes, vehiculos, vivienda, tipo;
    /**
     * Creates new form Registrar_inquilino
     */
    public Registrar_inquilino() {
        initComponents();
        Color c = new Color(240, 230, 140);
        this.getContentPane().setBackground(c);
        id_nuevo();
    }
    
    public void id_nuevo(){
        String sql ="SELECT MAX(ID) FROM USUARIOS WHERE ID LIKE '2202%'";
        Connection conect = null;
        try {
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            ResultSetMetaData rsmd = rs.getMetaData();
            if(rs.next()){
               id = rs.getInt("MAX(ID)") + 1;
               id_inqui.setText(String.valueOf(id));
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }finally{
            try {
                conect.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Error de desconexión", JOptionPane.ERROR_MESSAGE);
            }
        }

    }
    
    public int registrar(){
        int resultado = 0;
        nombre = nombre_inqui.getText();
        apellidoP = apellidoP_inqui.getText();
        apellidoM = apellidoM_inqui.getText();
        calle = calle_inqui.getText();
        contraseña = pass_inqui.getText();
        edad = Integer.parseInt(edad_inqui.getText());
        telefono = telefono_inqui.getText();
        ocupantes = Integer.parseInt(ocup_inqui.getText());
        vehiculos = Integer.parseInt(veh_inqui.getText());
        vivienda = Integer.parseInt(casaNo_inqui.getText());
        
        String sql="INSERT INTO USUARIOS VALUES("+id_inqui.getText()+",'"+nombre+"', '"+apellidoP+"', '"+ apellidoM+"', "+edad+", '"+genero+"','"
                                                 +telefono+"',"+ocupantes+", "+vehiculos+" , '"+calle+"' , "+vivienda+", '"+contraseña+"', 2)";
        
        Connection conect = null;
        try {
            conect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "isw", "isw");
            Statement st = conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                resultado=1;
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }finally{
            try {
                conect.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Error de desconexión", JOptionPane.ERROR_MESSAGE);
            }
        }

        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrar_inquilino = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        id_inqui = new javax.swing.JLabel();
        nombre_inqui = new javax.swing.JTextField();
        apellidoP_inqui = new javax.swing.JTextField();
        apellidoM_inqui = new javax.swing.JTextField();
        edad_inqui = new javax.swing.JTextField();
        telefono_inqui = new javax.swing.JTextField();
        opc_hombre_inqui = new javax.swing.JCheckBox();
        opc_mujer_inqui = new javax.swing.JCheckBox();
        ocup_inqui = new javax.swing.JTextField();
        veh_inqui = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        calle_inqui = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        casaNo_inqui = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass_inqui = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(920, 720));
        setSize(new java.awt.Dimension(920, 720));

        registrar_inquilino.setBackground(new java.awt.Color(240, 248, 255));
        registrar_inquilino.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        registrar_inquilino.setText("Registrar");
        registrar_inquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_inquilinoActionPerformed(evt);
            }
        });
        registrar_inquilino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registrar_inquilinoKeyPressed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(240, 248, 255));
        cancelar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Telefono");

        regresar.setBackground(new java.awt.Color(240, 248, 255));
        regresar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("Genero");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setText("No. de Ocupantes");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setText("No. de Vehiculos");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setText("Calle");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setText("Número de Casa");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel12.setText("Contraseña");

        id_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        id_inqui.setText("-----");

        nombre_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombre_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombre_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_inquiKeyTyped(evt);
            }
        });

        apellidoP_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        apellidoP_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apellidoP_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoP_inquiKeyTyped(evt);
            }
        });

        apellidoM_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        apellidoM_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                apellidoM_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoM_inquiKeyTyped(evt);
            }
        });

        edad_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        edad_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edad_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edad_inquiKeyTyped(evt);
            }
        });

        telefono_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        telefono_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefono_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono_inquiKeyTyped(evt);
            }
        });

        opc_hombre_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        opc_hombre_inqui.setText("Hombre");
        opc_hombre_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opc_hombre_inquiKeyPressed(evt);
            }
        });

        opc_mujer_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        opc_mujer_inqui.setText("Mujer");
        opc_mujer_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opc_mujer_inquiKeyPressed(evt);
            }
        });

        ocup_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ocup_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ocup_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ocup_inquiKeyTyped(evt);
            }
        });

        veh_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        veh_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                veh_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                veh_inquiKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("ID Inquilino");

        calle_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        calle_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calle_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                calle_inquiKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Nombre(s)");

        casaNo_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        casaNo_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                casaNo_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                casaNo_inquiKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("Apellido Paterno");

        pass_inqui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pass_inqui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_inquiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_inquiKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("Apellido Materno");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setText("Edad");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPinoSF.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(207, 167, 16));
        jLabel15.setText("Registrar Inquilino");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 83, 15), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(115, 115, 115)
                                .addComponent(id_inqui))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opc_hombre_inqui)
                                        .addGap(18, 18, 18)
                                        .addComponent(opc_mujer_inqui))
                                    .addComponent(nombre_inqui)
                                    .addComponent(apellidoP_inqui)
                                    .addComponent(apellidoM_inqui)
                                    .addComponent(edad_inqui)
                                    .addComponent(telefono_inqui)
                                    .addComponent(ocup_inqui)
                                    .addComponent(veh_inqui)
                                    .addComponent(calle_inqui)
                                    .addComponent(casaNo_inqui)
                                    .addComponent(pass_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(119, 119, 119)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registrar_inquilino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(regresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(registrar_inquilino)
                        .addGap(78, 78, 78)
                        .addComponent(cancelar)
                        .addGap(252, 252, 252))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id_inqui))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellidoP_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apellidoM_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edad_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(telefono_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(opc_hombre_inqui)
                            .addComponent(opc_mujer_inqui))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ocup_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(veh_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(calle_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(casaNo_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(pass_inqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrar_inquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_inquilinoActionPerformed
        try{
            boolean validacion = false, val_p= false, val_m = false, val_c = false, valS = false;
           char [] s ={'@','!','"','#','$','%','&','/','(',')','=','?','¿','¡','-',':',';','|','°','¬','*','+','.',',','_','<','>','[',']','{','}','´','¨','^','`',
                        '1','2','3','4','5','6','7','8','9','0'};
           char [] c ={'@','!','"','#','$','%','&','/','(',')','=','?','¿','¡','-',':',';','|','°','¬','*','+','.',',','_','<','>','[',']','{','}','´','¨','^','`'};
               for(int i = 0; i<nombre_inqui.getText().length();i++){
                   for(int j = 0;j<45; j++){
                       if(nombre_inqui.getText().charAt(i) == s[j]){
                           valS = true;
                       }
                   }
                   if(!valS){
                    if(nombre_inqui.getText().charAt(i) == ' ' && nombre_inqui.getText().charAt(0) != ' '){
                        validacion = true;
                    }   
                   }
               }
               validacion = false;
               for(int i = 0; i<apellidoP_inqui.getText().length();i++){
                   for(int j = 0;j<45; j++){
                       if(apellidoP_inqui.getText().charAt(i) == s[j]){
                           val_p= true;
                       }
                   }
                   if(!val_p){
                    if(apellidoP_inqui.getText().charAt(0) != ' ' && apellidoP_inqui.getText().charAt(i) == ' '){
                        validacion = true;
                    }   
                   }
               }
               validacion = false;
               for(int i = 0; i<apellidoM_inqui.getText().length();i++){
                   for(int j = 0;j<45; j++){
                       if(apellidoM_inqui.getText().charAt(i) == s[j]){
                           val_m = true;
                       }
                   }
                   if(!val_m){
                    if(apellidoM_inqui.getText().charAt(0) != ' ' && apellidoM_inqui.getText().charAt(i) == ' '){
                        validacion = true;
                    }   
                   }
               }
               validacion = false;
               for(int i = 0; i<calle_inqui.getText().length();i++){
                   for(int j = 0;j<35; j++){
                       if(calle_inqui.getText().charAt(i) == c[j]){
                           val_c = true;
                       }
                   }
                   if(!val_c){
                    if(calle_inqui.getText().charAt(0) != ' ' && calle_inqui.getText().charAt(i) == ' '){
                        validacion = true;
                    }   
                   }
               }
               
            if(!id_inqui.getText().isEmpty() && !nombre_inqui.getText().isEmpty() && !apellidoP_inqui.getText().isEmpty() && !apellidoM_inqui.getText().isEmpty() && !edad_inqui.getText().isEmpty()
               && !telefono_inqui.getText().isEmpty() && !ocup_inqui.getText().isEmpty() && !veh_inqui.getText().isEmpty() && 
                    !calle_inqui.getText().isEmpty() && !casaNo_inqui.getText().isEmpty() && !pass_inqui.getText().isEmpty()){
                if(!valS && (validacion || nombre_inqui.getText().matches("^[a-zA-Z]*$"))){
                    if(!val_p && (validacion || apellidoP_inqui.getText().matches("^[a-zA-Z]*$"))){
                        if(apellidoM_inqui.getText().matches("^[a-zA-Z]*$")){
                            if(!calle_inqui.getText().startsWith(" ")){
                                if(edad_inqui.getText().matches("^[0-9]*$")){
                                    if(telefono_inqui.getText().matches("^[0-9]*$")){
                                        if(opc_hombre_inqui.isSelected() && !opc_mujer_inqui.isSelected()){
                                            genero = "H";
                                            if(registrar()==1){
                                                JOptionPane.showMessageDialog(null, "Registrado");
                                                nombre_inqui.setText("");
                                                apellidoP_inqui.setText("");
                                                apellidoM_inqui.setText("");
                                                calle_inqui.setText("");
                                                pass_inqui.setText("");
                                                edad_inqui.setText("");
                                                telefono_inqui.setText("");
                                                ocup_inqui.setText("");
                                                veh_inqui.setText("");
                                                casaNo_inqui.setText("");
                                                opc_hombre_inqui.setSelected(false);
                                                id_nuevo();
                                            }else{
                                                JOptionPane.showMessageDialog(null, "No Registrado", null, JOptionPane.WARNING_MESSAGE);
                                                nombre_inqui.setText("");
                                                apellidoP_inqui.setText("");
                                                apellidoM_inqui.setText("");
                                                calle_inqui.setText("");
                                                pass_inqui.setText("");
                                                edad_inqui.setText("");
                                                telefono_inqui.setText("");
                                                ocup_inqui.setText("");
                                                veh_inqui.setText("");
                                                casaNo_inqui.setText("");
                                                opc_hombre_inqui.setSelected(false);
                                            }
                                        }else if(!opc_hombre_inqui.isSelected() && opc_mujer_inqui.isSelected()){
                                            genero = "M";
                                            if(registrar()==1){
                                                JOptionPane.showMessageDialog(null, "Registrado");
                                                nombre_inqui.setText("");
                                                apellidoP_inqui.setText("");
                                                apellidoM_inqui.setText("");
                                                calle_inqui.setText("");
                                                pass_inqui.setText("");
                                                edad_inqui.setText("");
                                                telefono_inqui.setText("");
                                                ocup_inqui.setText("");
                                                veh_inqui.setText("");
                                                casaNo_inqui.setText("");
                                                opc_mujer_inqui.setSelected(false);
                                                id_nuevo();
                                            }else{
                                                JOptionPane.showMessageDialog(null, "No Registrado", null, JOptionPane.WARNING_MESSAGE);
                                                nombre_inqui.setText("");
                                                apellidoP_inqui.setText("");
                                                apellidoM_inqui.setText("");
                                                calle_inqui.setText("");
                                                pass_inqui.setText("");
                                                edad_inqui.setText("");
                                                telefono_inqui.setText("");
                                                ocup_inqui.setText("");
                                                veh_inqui.setText("");
                                                casaNo_inqui.setText("");
                                                opc_mujer_inqui.setSelected(false);
                                            }
                                        }else if(!opc_hombre_inqui.isSelected() && !opc_mujer_inqui.isSelected()){
                                            JOptionPane.showMessageDialog(null, "No se ha seleccionado genero", null, JOptionPane.WARNING_MESSAGE);
                                        }else{
                                            JOptionPane.showMessageDialog(null, "Selecciona un solo genero", null, JOptionPane.WARNING_MESSAGE);
                                            opc_hombre_inqui.setSelected(false);
                                            opc_mujer_inqui.setSelected(false);
                                        }
                                }else{
                                    JOptionPane.showMessageDialog(null, "!Caracteres invalidos!.", "Alerta", JOptionPane.ERROR_MESSAGE);
                                    telefono_inqui.setText("");
                                    telefono_inqui.requestFocus();
                                }
                                }else{
                                    JOptionPane.showMessageDialog(null, "!Caracteres invalidos!.", "Alerta", JOptionPane.ERROR_MESSAGE);
                                    edad_inqui.setText("");
                                    edad_inqui.requestFocus();
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "El campo de calle no debe empezar con espacio\n"+ "en blanco o estar vacia.", "Alerta", JOptionPane.ERROR_MESSAGE);
                                calle_inqui.setText("");
                                calle_inqui.requestFocus();
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Solo se permiten letras en el apellido materno\n"+"ni espacios en blanco al principio.", "Alerta", JOptionPane.ERROR_MESSAGE);
                            apellidoM_inqui.setText("");
                            apellidoM_inqui.requestFocus();
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Solo se permiten letras en el apellido paterno\n"+"ni espacios en blanco al principio.", "Alerta", JOptionPane.ERROR_MESSAGE);
                        apellidoP_inqui.setText("");
                        apellidoP_inqui.requestFocus();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Solo se permiten letras en el nombre.\n"+ "sin espacios al principio.", "Alerta", JOptionPane.ERROR_MESSAGE);
                    nombre_inqui.setText("");
                    nombre_inqui.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Alerta!", JOptionPane.WARNING_MESSAGE);
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "¡Caracteres invalidos!", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrar_inquilinoActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void nombre_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_inquiKeyTyped
        if(nombre_inqui.getText().length()>19){
            evt.consume();
        }
    }//GEN-LAST:event_nombre_inquiKeyTyped

    private void apellidoP_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoP_inquiKeyTyped
        if(apellidoP_inqui.getText().length()>19){
            evt.consume();
        }
    }//GEN-LAST:event_apellidoP_inquiKeyTyped

    private void apellidoM_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoM_inquiKeyTyped
        if(apellidoM_inqui.getText().length()>19){
            evt.consume();
        }
    }//GEN-LAST:event_apellidoM_inquiKeyTyped

    private void edad_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edad_inquiKeyTyped
        if(edad_inqui.getText().length()>2){
            evt.consume();
        }
    }//GEN-LAST:event_edad_inquiKeyTyped

    private void telefono_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_inquiKeyTyped
        if(telefono_inqui.getText().length()>9){
            evt.consume();
        }
    }//GEN-LAST:event_telefono_inquiKeyTyped

    private void ocup_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ocup_inquiKeyTyped
        if(ocup_inqui.getText().length()>1){
            evt.consume();
        }
    }//GEN-LAST:event_ocup_inquiKeyTyped

    private void veh_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_veh_inquiKeyTyped
        if(veh_inqui.getText().length()>1){
            evt.consume();
        }
    }//GEN-LAST:event_veh_inquiKeyTyped

    private void calle_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calle_inquiKeyTyped
        if(calle_inqui.getText().length()>49){
            evt.consume();
        }
    }//GEN-LAST:event_calle_inquiKeyTyped

    private void casaNo_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_casaNo_inquiKeyTyped
        if(casaNo_inqui.getText().length()>4){
            evt.consume();
        }
    }//GEN-LAST:event_casaNo_inquiKeyTyped

    private void pass_inquiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_inquiKeyTyped
        if(pass_inqui.getText().length()>9){
            evt.consume();
        }
    }//GEN-LAST:event_pass_inquiKeyTyped

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        JOptionPane.showMessageDialog(null, "Regresando al menu");
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void nombre_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            apellidoP_inqui.requestFocus();
        }
    }//GEN-LAST:event_nombre_inquiKeyPressed

    private void apellidoP_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoP_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            apellidoM_inqui.requestFocus();
        }
    }//GEN-LAST:event_apellidoP_inquiKeyPressed

    private void apellidoM_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoM_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            edad_inqui.requestFocus();
        }
    }//GEN-LAST:event_apellidoM_inquiKeyPressed

    private void edad_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edad_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            telefono_inqui.requestFocus();
        }
    }//GEN-LAST:event_edad_inquiKeyPressed

    private void telefono_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            opc_hombre_inqui.requestFocus();
        }
    }//GEN-LAST:event_telefono_inquiKeyPressed

    private void opc_hombre_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opc_hombre_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            opc_hombre_inqui.setSelected(true);
            ocup_inqui.requestFocus();
        }
    }//GEN-LAST:event_opc_hombre_inquiKeyPressed

    private void opc_mujer_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opc_mujer_inquiKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            opc_mujer_inqui.setSelected(true);
            ocup_inqui.requestFocus();
        }
    }//GEN-LAST:event_opc_mujer_inquiKeyPressed

    private void ocup_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ocup_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            veh_inqui.requestFocus();
        }
    }//GEN-LAST:event_ocup_inquiKeyPressed

    private void veh_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_veh_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calle_inqui.requestFocus();
        }
    }//GEN-LAST:event_veh_inquiKeyPressed

    private void calle_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calle_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            casaNo_inqui.requestFocus();
        }
    }//GEN-LAST:event_calle_inquiKeyPressed

    private void casaNo_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_casaNo_inquiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            pass_inqui.requestFocus();
        }
    }//GEN-LAST:event_casaNo_inquiKeyPressed

    private void pass_inquiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_inquiKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           registrar_inquilino.requestFocus();
        }
    }//GEN-LAST:event_pass_inquiKeyPressed

    private void registrar_inquilinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrar_inquilinoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            registrar_inquilino.doClick();
        }
    }//GEN-LAST:event_registrar_inquilinoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_inquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_inquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_inquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_inquilino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_inquilino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoM_inqui;
    private javax.swing.JTextField apellidoP_inqui;
    private javax.swing.JTextField calle_inqui;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField casaNo_inqui;
    private javax.swing.JTextField edad_inqui;
    private javax.swing.JLabel id_inqui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre_inqui;
    private javax.swing.JTextField ocup_inqui;
    private javax.swing.JCheckBox opc_hombre_inqui;
    private javax.swing.JCheckBox opc_mujer_inqui;
    private javax.swing.JTextField pass_inqui;
    private javax.swing.JButton registrar_inquilino;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField telefono_inqui;
    private javax.swing.JTextField veh_inqui;
    // End of variables declaration//GEN-END:variables
}
